    1. Aufnahme und Analyse eines Grauwertkeiles
In diesem Versuch überprüfen wir, wie gut die Webcam am Arbeitsplatz einen stufenförmigen
Grauwertverlauf aufnehmen kann. Da das aufgenommene Muster vorher bekannt ist, kann
man anhand der Aufnahme die Wiedergabequalität messen. In unserem Fall sollte der
Grauwert innerhalb jeder Stufe konstant sein. Die reale Aufnahme wird aber aufgrund von
Bildfehlern und Sensorrauschen Abweichungen aufweisen.
• Nehmen Sie den Grauwertkeil (im Labor vorhanden) mit der Webcam an Ihrem Arbeitsplatz so auf, dass er das gesamte Bildfeld ausfüllt, den Helligkeitsbereich möglichst gut
ausschöpft und die Grauwertstufen parallel zu den Bildrändern verlaufen. Stellen Sie
sicher, dass kein Teil des Grauwertkeils in der Hell- oder Dunkelsättigung verschwindet.
Nutzen Sie zu diesem Zweck das Python-Paket OpenCV-Python. Ein Kurzanleitung zur
Installation, zum Einlesen von Bildern und Veränderung der Belichtungsparameter der
Kamera finden Sie in Moodle. Notieren Sie, welche Belichtungsparameter Sie eingestellt
haben, und die Entfernung zwischen Kamera und Testbild. Stellen Sie sicher, dass Sie
die Belichtungsparameter im Verlauf der Versuche nicht mehr verändern. Speichern Sie
das Bild für die Weiterverarbeitung und für das Protokoll (Befehl: cv2.imwrite())
im verlustfreien Format png ab (das sonst übliche JPEG-Format ist verlustbehaftet).

• Schreiben Sie ein Pythonskript, dass das Bild einliest (Befehl: pyopencv.imread())
und die einzelnen Grauwertstufen als Unterbilder aus dem Originalbild ausliest. Schauen
Sie sich dazu nochmals das Thema Indizierung und Index Slicing aus der PythonEinführung an.
Die Webcam liefert standardmäßig nur Farbbilder. Ein Farbbild können Sie mit der
Funktion cv2.cvtColor() in ein Grauwertbild umwandeln. Anzeigen lässt sich das
Bild bequem mit dem Befehl cv2.imshow(). Achten Sie darauf, dass die Unterbilder
möglichst viele Pixel der jeweiligen Stufe umfassen, ohne die Stufenränder zu berühren.
• Bestimmen Sie für jede Stufe den Mittelwert und die Standardabweichung der Grauwerte und tragen Sie diese in eine Tabelle ein. Die zugehörigen Befehle finden sich
ebenfalls in der Python-Einführung.
Ein wichtiges Detail: wir bestimmen hier nicht die Standardabweichung des Mittelwertes,
sondern nur die normale Standardabweichung, denn uns interessiert hier nicht das
Vertrauensintervall des Mittelwertes, sondern die Streuung der Messwerte. Damit
können wir in der letzten Aufgabe die Qualität unserer Kalibrierung überprüfen.


In [26]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

#grauskalabild = cv2.imread("Bilder\graustufe2.png", cv2.COLOR_BGR2GRAY)
#plt.imshow(grauskalabild, cmap=plt.get_cmap('gray'));
grauskalabild = cv2.imread(f"Bilder\graustufe2.png", cv2.IMREAD_GRAYSCALE)
#grauskalabild = grauskalabild[50:, :]
#cv2.imshow('Grauwertkeil.png', grauskalabild)

grey = []
grey.append(grauskalabild[10:430,0:50])
grey.append(grauskalabild[10:430,100:150])
grey.append(grauskalabild[10:430,250:300])
grey.append(grauskalabild[10:430,420:470])
grey.append(grauskalabild[10:430,570:620])
#cv2.imshow('test',grauskalabild[10:430,0:50])

#plt.imshow(grey[0], cmap=plt.get_cmap('gray'))
#np.array(grey[1]).shape
mean = []
for i in range(0,5):
    mean.append(np.mean(grey[i]))
mean = np.array(mean)

std = []
for i in range(0,5):
    std.append(np.std(grey[i]))
std = np.array(std)

print("Mittelwerte:")
print(mean)
print("Standardabweichung:")
print(std)

Mittelwerte:
[  0.          10.56133333  64.41571429 108.55638095 154.17861905]
Standardabweichung:
[ 0.         10.50216078  1.66348479  2.38873592  2.84709543]


    2. Aufnahme eines Dunkelbildes
Nicht jeder Pixel einer Kamera liefert den Grauwert 0, wenn der Sensor abgedeckt ist. Das liegt
zum einen am thermischen Rauschen der Ausleseelektronik, zum anderen am sogenannten
Dunkelstrom, das aufgrund von Fertigungstoleranzen und von spontan durch Wärmezufuhr
entstehenden Ladungsträgerpaaren zu einem leicht unterschiedlichen Nullpunkt jedes Pixels
führt. Diesen pixelweisen Offset kann man durch Erstellung eines Dunkelbildes eliminieren,
den man von jeder Aufnahme subtrahiert. Dadurch wird ein Großteil des Rauschens aus der
Aufnahme entfernt. Achtung: der Offset jedes Pixels hängt stark von der Belichtungszeit ab,
d.h. im Prinzip braucht man für jede unterschiedliche Belichtungszeit ein eigenes Dunkelbild!
Deshalb ist es wichtig, bei der Aufnahme des Dunkelbildes die Belichtungsparameter konstant
auf den gleichen Wert der zu korrigierenden Aufnahme zu stellen. Vom Gesichtspunkt der
Kalibrierung her bestimmen wir mit dem Dunkelbild alle Nullpunkte jeden einzelnen Pixels
des gesamtem Sensors.

Vorgehensweise:
• Stellen Sie die Belichtungsparameter genau gleich wie bei der Aufnahme des Grauwertkeiles ein. Decken Sie das Objektiv der Kamera so ab, dass das Bild komplett schwarz
wird. Machen Sie 10 Aufnahmen.
• Schreiben Sie ein Pythonskript, dass die 10 Bilder einliest, in double umwandelt, die
Farbbilder in Grauwertbilder umrechnet und ihren pixelweisen Mittelwert berechnet.
Sie erhalten also nicht einen einzigen Mittelwert wie in Aufgabe 1, sondern ein ganzes
Bild von Mittelwerten in derselben Größe wie die Einzelaufnahmen. Auf diese Weise
wird das thermische Ausleserauschen eliminiert, es bleibt nur noch der Offset bzw. der
Dunkelstrom jedes Pixels übrig. Das Mittelwertbild ist das Dunkelbild für die von
Ihnen gewählte Belichtungszeit. Stellen Sie das Dunkelbild kontrastmaximiert dar und
nehmen Sie es in das Protokoll auf.
• Schreiben Sie ein Pythonskript, dass das Dunkelbild einliest, von einem Eingabebild
subtrahiert und das korrigierte Bild abspeichert. Wir werden das Programm dann in
den folgenden Aufgaben erweitern.

In [27]:
dunkelbild = []
for i in range(0,10):
    dunkelbild.append(cv2.imread(f"Bilder\Dunkelbild{i}.png", cv2.COLOR_BGR2GRAY))
dunkelbild = np.array(dunkelbild, dtype = np.float64)
print(dunkelbild.shape)
dunkelbildmean = np.mean(dunkelbild, axis=0)
print(dunkelbildmean.shape)
print(grauskalabild.shape)
#dunkelbildmean.shape
#plt.imshow(dunkelbildmean, cmap=plt.get_cmap('gray'))
#dunkelbild_kontrastmax = cv2.equalizeHist(dunkelbildmean.astype('uint8'))
alpha = 1.5 # Contrast control (1.0-3.0)
beta = 0 # Brightness control (0-100)

dunkelbild_kontrastmax = cv2.convertScaleAbs(dunkelbildmean, alpha=alpha, beta=beta)
grauwertkeil = grauskalabild - dunkelbildmean
cv2.imwrite("dunkelbild_kontrastmax.png", dunkelbild_kontrastmax)
cv2.imwrite("dunkelbild_mean.png", dunkelbildmean)
cv2.imwrite("Grauwertkeil_-dunkelbild.png", grauwertkeil)

(10, 480, 640)
(480, 640)
(480, 640)


True

    3. Aufnahme eines Weißbildes
Obwohl die einzelnen Pixel einer Kamera eine hervorragende Linearität mit der Beleuchtungsstärke aufweisen, ist ihre Sensitivität aufgrund von Fertigungstoleranzen nicht völlig
gleich. Zusätzlich kommt noch die sogenannte Vignettierung hinzu, d.h. die Optik der Kamera
übeträgt die Helligkeit nicht gleichmäßig auf den Sensor. Typischerweise findet man eine
Abdunkelung des Bildes zu den Rändern hin. Zur Kompensation dieser Effekte nimmt man
ein sogenanntes Weißbild auf. Dazu braucht man eine möglichst homogene Fläche, z.B. ein
Blatt Papier oder den wolkenlosen Himmel. Durch Division durch das Weissbild kann man
die unterschiedlichen Sensitivitäten der einzelnen Pixel herausrechnen. Leider hängt das
Weißbild vom eingestellten Fokus des Kameraobjektives ab, d.h. im Prinzip braucht man für
jede Fokuseinstellung ein eigenes Weißbild. In unserem Fall bedeutet das, dass das Weißbild
in der gleichen Entfernung wie das zu korrigierende Bild aufgenommen werden muss.
Vom Gesichtspunkt der Kalibrierung her nehmen wir mit dem Weißbild einen zweiten Punkt
der Kennlinie jeden einzelnen Pixels auf. Zusammen mit dem Dunkelbild haben wir damit
die Kennlinie für alle Pixel gleichzeitig und eindeutig bestimmt: wir wissen an jeder Stelle des
Bildes die Steigung und den Nullpunkt und können durch Subtraktion des Dunkelbildes und
Division durch das Weißbild die tatsächliche Intensität des einfallenden Lichtes bestimmen.
Vorgehensweise:
• Nehmen Sie ein leeres Blatt Papier in der gleichen Entfernung wie das Testbild auf.
Achten Sie darauf, die Belichtung auf 30-50% der Hellsättigung einzustellen. Wichtig
ist auch, dass die Helligkeit des Blattes so gleichmäßig wie möglich ist, also keine
Schatten oder unterschiedlich helle Beleuchtung. Machen Sie auch hier 10 Aufnahmen
zur Elimination des thermischen Rauschens.
• Schreiben Sie ein Pythonskript, dass die 10 Bilder einliest und ihren Mittelwert
berechnet. Subtrahieren Sie von dem Mittelwertbild das Dunkelbild und speichern Sie
das resultierende Weißbild ab. Stellen Sie das Weißbild kontrastmaximiert dar und
nehmen Sie es in das Protokoll auf.
• Erweitern Sie das Pythonskript zur Subtraktion des Dunkelbildes aus Aufgabe 2 so,
dass das Weißbild eingelesen, in double umgewandelt wird und so normiert wird, dass
sein Mittelwert 1 ist. Das durch Abzug des Dunkelbildes korrigierte Eingangsbild wird
anschliessend durch das normierte Weißbild dividiert.

In [28]:
weißbild = []
for i in range(1,11):
    weißbild.append(cv2.imread(f"Bilder\weisbild{i}.png", cv2.IMREAD_GRAYSCALE))
weißbild = np.array(weißbild, dtype = np.float64)
weißbildmean = np.mean(weißbild, axis=0)
weißbildmean = weißbildmean - dunkelbildmean
#plt.imshow(weißbildmean, cmap=plt.get_cmap('gray'))
w = np.mean(weißbildmean)
weißbildmean = weißbildmean / w
cv2.imwrite("weißbild_mean.png", weißbildmean)

#weißbild_kontrastmax = cv2.equalizeHist(weißbildmean.astype('uint8'))
alpha = 1.5 # Contrast control (1.0-3.0)
beta = 0 # Brightness control (0-100)

weißbild_kontrastmax = cv2.convertScaleAbs(weißbildmean, alpha=alpha, beta=beta)
cv2.imwrite("weißbild_kontrastmax.png", weißbild_kontrastmax)

grauwertkeil = grauwertkeil / weißbildmean
cv2.imwrite("Grauwertkeil_-dunkelbild_divweißbild.png", grauwertkeil)

True

    4. Pixelfehler
Je nach Qualität des Bildsensors entstehen beim Fertigungsprozess eine Anzahl von funktionsuntüchtigen Pixeln. Es gibt dead pixels, die immer auf ihrem niedrigsten Wert steckenbleiben,
stuck pixels, die immer auf ihrem Maximalwert bleiben, und sogenannte hot pixels, die bei
längeren Belichtungszeiten in die Sättigung gehen. Stuck und hot pixels entdeckt man am
einfachsten im Dunkelbild, bei dem diese Pixel als helle Punkte auffallen. Dead Pixels findet
man im Weißbild, wo sie als dunkle Punkte auffallen. Je nach Anwendung werden diese
Pixelwerte im zu korrigierenden Bild durch Interpolation aus ihren Nachbarwerten ersetzt,
so dass sie nicht mehr auffallen.
Vorgehensweise:
• Überprüfen Sie Ihr Dunkelbild auf dem Bildschirm auf stuck und hot pixels und Ihr
Weißbild auf dead pixels. Markieren Sie diese im Bild und fügen es ins Protokoll ein.
• Korrigieren Sie mithilfe Ihres Programms aus Aufgabe 3 das Bild des Grauwertkeils
aus Aufgabe 1, speichern Sie es ab und bauen Sie es in Ihr Protokoll ein.
• Werten Sie nun erneut das korrigierte Bild aus Aufgabe 4 mit diesem Programm aus und
erstellen Sie die zugehörige Tabelle wie in Aufgabe 1. Ergibt sich eine Verbesserung?


In [29]:
deadpixel = np.argwhere(weißbild_kontrastmax[:, :] == 0)
stuckpixel = np.argwhere(dunkelbild_kontrastmax[:, :] == 255)
stuckpixelbild = grauskalabild.copy()

# cv2 drawfunktion die die pixel aufmalt
for (x, y) in stuckpixel:
    stuckpixelbild = cv2.circle(img=stuckpixelbild, center=(y, x), radius=1, color=(255, 0, 0))


cv2.imwrite("stuckpixelbild.png", stuckpixelbild)

deadpixelbild = grauskalabild.copy()
for (x, y) in deadpixel:
    deadpixelbild = cv2.circle(img=deadpixelbild , center=(y, x), radius=1, color=(0, 0, 255))
cv2.imwrite("deadpixelbild.png", deadpixelbild);

In [30]:
grey_corrected = []
grey_corrected.append(grauwertkeil[20:460, 10:80])
grey_corrected.append(grauwertkeil[20:460, 110:180])
grey_corrected.append(grauwertkeil[20:460, 250:320])
grey_corrected.append(grauwertkeil[20:460, 400:470])
grey_corrected.append(grauwertkeil[20:460, 530:600])

mean_corrected = []
for i in range(0,5):
    mean_corrected.append(np.mean(grey_corrected[i]))
mean_corrected = np.array(mean_corrected)

std_corrected = []
for i in range(0,5):
    std_corrected.append(np.std(grey_corrected[i]))
std_corrected = np.array(std_corrected)

print("Mittelwerte:")
print(mean)
print("Standardabweichung:")
print(std)
print("Mittelwerte korrigiertes Bild:")
print(mean_corrected)
print("Standardabweichung korrigiertes Bild:")
print(std_corrected)

Mittelwerte:
[  0.          10.56133333  64.41571429 108.55638095 154.17861905]
Standardabweichung:
[ 0.         10.50216078  1.66348479  2.38873592  2.84709543]
Mittelwerte korrigiertes Bild:
[  0.28353982  14.42401552  62.22354615 107.16683718 140.55299634]
Standardabweichung korrigiertes Bild:
[ 2.46410115  9.53170039  1.71496627  3.52672566 26.11821603]
